<script>
  // Screenshot harness for the README. Renders the app's own shell and
  // components against data the Rust backend decoded from the ASAM demo pair,
  // so the images show real values rather than mock-ups.
  //
  // Not shipped — regenerated by docs/screenshots/capture.sh.
  import FileMenu from '$lib/components/FileMenu.svelte';
  import HexViewer from '$lib/components/HexViewer.svelte';
  import DataView from '$lib/components/DataView.svelte';
  import MapEditor from '$lib/components/MapEditor.svelte';
  import rows from './rows.json';
  import stats from './stats.json';
  import details from './details.json';
  import records from './records.json';

  const q = new URLSearchParams(typeof location === 'undefined' ? '' : location.search);
  const shot = q.get('shot') ?? 'data';

  const SCENES = {
    // Aimed at the calibration block: the rest of the image is FF padding,
    // which shows the viewer but says nothing about the file.
    hex:  { mode: 'hex',  sel: null, goto: 0x810000,
            status: 'ASAP2_Demo_V171.hex — 0x00810000' },
    data: { mode: 'data', sel: 'ASAM.C.CURVE.STD_AXIS',
            status: 'ASAM.C.CURVE.STD_AXIS → -3 … 71 hours' },
    map:  { mode: 'data', sel: 'ASAM.C.MAP.STD_AXIS.STD_AXIS', editor: true,
            status: 'ASAM.C.MAP.STD_AXIS.STD_AXIS value[6] → 6' },
  };
  const scene = SCENES[shot] ?? SCENES.data;

  // Dark by default: it is how the app is usually run and it reads well
  // against both GitHub themes.
  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute('data-theme', q.get('theme') ?? 'dark');
  }

  let selected = $state(scene.sel);
  const detail = $derived(details[selected] ?? null);
</script>

<div class="app-shell">
  <FileMenu
    hasFile={true} canUndo={true} canRedo={false} hasSelection={false}
    viewMode={scene.mode} a2lName={scene.mode === 'data' ? 'ASAP2_Demo_V171.a2l' : ''}
    cdfxReady={scene.mode === 'data'}
  />
  <div class="content-area">
    <main class="viewer-area">
      {#if scene.mode === 'hex'}
        <HexViewer {records} editable={true}
                   gotoTarget={scene.goto ? { addr: scene.goto, seq: 1 } : null} />
      {:else}
        <DataView {rows} {stats} {detail} {selected} showType={true}
                  onSelect={(n) => (selected = n)} />
      {/if}
    </main>
  </div>
  <footer class="statusbar"><span>{scene.status}</span></footer>
</div>

{#if scene.editor}
  <MapEditor open={true} row={rows.find((r) => r.name === selected)} {detail}
             onClose={() => {}} />
{/if}

<style>
  :global(body) { margin: 0; }
  .app-shell { display: flex; flex-direction: column; height: 100vh; }
  .content-area { flex: 1; display: flex; overflow: hidden; min-height: 0; }
  .viewer-area { flex: 1; overflow: hidden; min-width: 0; }
  /* Lifted from the app shell so the harness frames the view identically. */
  .statusbar {
    display: flex; align-items: center; height: 22px; padding: 0 10px;
    background: var(--c-accent); color: #fff; font-size: 11.5px;
    letter-spacing: 0.01em; white-space: nowrap; flex-shrink: 0;
  }
</style>
