<script>
  // Screenshot harness for the README. Renders the app's own shell and
  // components against data the Rust backend decoded from the ASAM demo pair,
  // so the images show real values rather than mock-ups.
  //
  // Not shipped — regenerated by docs/screenshots/capture.sh.
  import FileMenu from '$lib/components/FileMenu.svelte';
  import HexViewer from '$lib/components/HexViewer.svelte';
  import SegmentList from '$lib/components/SegmentList.svelte';
  import DataInspector from '$lib/components/DataInspector.svelte';
  import DataView from '$lib/components/DataView.svelte';
  import MapEditor from '$lib/components/MapEditor.svelte';
  import rows from './rows.json';
  import stats from './stats.json';
  import details from './details.json';
  import records from './records.json';

  const q = new URLSearchParams(typeof location === 'undefined' ? '' : location.search);
  const shot = q.get('shot') ?? 'data';

  const SCENES = {
    // Aimed at the calibration block: the rest of the image is FF padding,
    // which shows the viewer but says nothing about the file.
    // Both side panes on: they belong to the hex view, and the shot is the
    // one place to show what they hold.
    hex:  { mode: 'hex',  sel: null, goto: 0x810000, panes: true,
            status: 'ASAP2_Demo_V171.hex — 0x00810000' },
    data: { mode: 'data', sel: 'ASAM.C.CURVE.STD_AXIS',
            status: 'ASAM.C.CURVE.STD_AXIS → -3 … 71 hours' },
    // This map rather than the 4x5 one: its values fold across both
    // directions and its X breakpoints run 0..5 then 13, 15, so the surface
    // shows shape and true spacing instead of a flat ramp.
    map:  { mode: 'data', sel: 'ASAM.C.MAP.COM_AXIS.FIX_AXIS', editor: true,
            below: '3D',
            status: 'ASAM.C.MAP.COM_AXIS.FIX_AXIS value[9] → 10' },
  };
  const scene = SCENES[shot] ?? SCENES.data;

  // capture.sh passes the theme; light is the default when the harness is
  // opened by hand, matching what the README ships.
  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute('data-theme', q.get('theme') ?? 'light');
  }

  let selected = $state(scene.sel);
  let topAddress = $state(scene.goto ?? 0);
  const detail = $derived(details[selected] ?? null);

  // Which panel sits under the grid is the editor's own state, so the harness
  // presses the control rather than reaching inside it — the shot then shows
  // exactly what a user would see after the same click.
  $effect(() => {
    if (!scene.below) return;
    const btn = [...document.querySelectorAll('.seg-btn')].find(
      (b) => b.textContent.trim() === scene.below,
    );
    if (btn && !btn.classList.contains('on')) btn.click();
  });
</script>

<div class="app-shell">
  <FileMenu
    hasFile={true} canUndo={true} canRedo={false} hasSelection={false}
    viewMode={scene.mode} a2lName={scene.mode === 'data' ? 'ASAP2_Demo_V171.a2l' : ''}
    cdfxReady={scene.mode === 'data'}
  />
  <div class="content-area">
    <main class="viewer-area">
      {#if scene.mode === 'hex'}
        <HexViewer {records} editable={true}
                   gotoTarget={scene.goto ? { addr: scene.goto, seq: 1 } : null}
                   onTopAddress={(a) => (topAddress = a)} />
      {:else}
        <DataView {rows} {stats} {detail} {selected} showType={true}
                  onSelect={(n) => (selected = n)} />
      {/if}
    </main>

    <!-- Same structure as the app shell, so the panes sit where they really do. -->
    {#if scene.panes}
      <aside class="side-panel">
        <div class="side-section">
          <SegmentList {records} topAddress={topAddress} />
        </div>
        <div class="side-divider"></div>
        <div class="side-section">
          <DataInspector {records} address={scene.goto ?? 0} pinned={true} />
        </div>
      </aside>
    {/if}
  </div>
  <footer class="statusbar"><span>{scene.status}</span></footer>
</div>

{#if scene.editor}
  <MapEditor open={true} row={rows.find((r) => r.name === selected)} {detail}
             onClose={() => {}} />
{/if}

<style>
  :global(body) { margin: 0; }
  .app-shell { display: flex; flex-direction: column; height: 100vh; }
  .content-area { flex: 1; display: flex; overflow: hidden; min-height: 0; }
  .viewer-area { flex: 1; overflow: hidden; min-width: 0; }
  .side-panel {
    width: 280px; flex-shrink: 0; display: flex; flex-direction: column;
    border-left: 1px solid var(--c-hover); overflow: hidden; background: var(--c-bg);
  }
  .side-section { flex: 1; min-height: 0; overflow: hidden; display: flex; flex-direction: column; }
  .side-divider { height: 1px; flex-shrink: 0; background: var(--c-hover); }
  /* Lifted from the app shell so the harness frames the view identically. */
  .statusbar {
    display: flex; align-items: center; height: 22px; padding: 0 10px;
    background: var(--c-accent); color: #fff; font-size: 11.5px;
    letter-spacing: 0.01em; white-space: nowrap; flex-shrink: 0;
  }
</style>
